export const GET_PROFILE = 'GET_PROFILE';

export const GET_PROFILE_LIST = 'GET_PROFILE_LIST';

export const GET_BLOG = 'GET_BLOG';

export const GET_BLOG_LIST = 'GET_BLOG_LIST';

export const GET_BLOG_RATINGS = 'GET_BLOG_RATINGS';

export const GET_RATINGS = 'GET_RATINGS';

export const GET_ERRORS = 'GET_ERROR';

export const GET_SUCCESS_MESSAGE = 'GET_SUCCESS_MESSAGE';

export const RESET_FLASH_MESSAGE = 'RESET_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REGISTER_USER = 'REGISTER_USER';

export const LOGOUT_USER = 'LOGOUT_USER';
